### ISSUE TITLE
[API] Searchresult Limitation

### ISSUE THREAD

**Issue by PCSuchti** [hummingbird-me/hummingbird#378]
Hi,

I'd like to request changing the limit on searchresults in the API to at least 20.
In many cases 5 results just is not enough to find what you're looking for.
e.g. searching for "Naruto" or "One Piece" only returns a fraction of the available movies and specials.
I don't think it should cause that much additional stress on the servers.

Thanks in advance!

**Comment by cybrox** [comment]
Hi,

I think for APIv2, search should definitely get an option to set a page and (capped) per-page parameter for this. I don't know if changing this in APIv1 would make sense since we want to keep that as static as possible.

Until that is ready, you could use the internal API endpoint "full" to get 20 results for anime and manga each as well as a few user search results as an alternative. https://hummingbird.me/search.json?query=Naruto&type=full

**Comment by vikhyat** [comment]
I think a PR to change APIv1 result limit from 5 to 20 would be fine.

**Comment by cybrox** [comment]
There are ways to break an app like this but your code would have to be really bad for this.
Anywas, PR has been merged, limit is 20 now. @PCSuchti

**Comment by PCSuchti** [comment]
Thanks a lot!
I didn't expect this to be resolved this fast ^^ 
@cybrox you're right about APIv2. Maybe there could even be more options like filtering results by years or if it has finished airing. But that's for later ... I'm closing this issue.

**Comment by cybrox** [comment]
@PCSuchti Filter possibilities like filtering results by year, airing state, genre and more technically already exists internally for the *explore* page. Once that is cleaned up and rolled out, I guess putting these parts together for a powerful search API would definitely be possible.

Thanks for the feedback btw.
