### ISSUE TITLE
User edit profile link its broken 

### ISSUE THREAD

**Issue by nivla** [hummingbird-me/hummingbird#387]
When I'm in https://hummingbird.me/anime/filter/all , when i click the user menu dropdown and clicked the link edit profile, it is broken and return error 500.

![screenshot-hummingbird me 2015-01-18 21-07-32 1](https://cloud.githubusercontent.com/assets/2448098/5837941/f1a6f1ee-a159-11e4-9cbe-ea46db5fad7f.png)

I also notice that the dropdown menu user from dashboard page its different from another pages.
Its that right?

![screenshot-hummingbird me 2015-01-18 21-13-00](https://cloud.githubusercontent.com/assets/2448098/5837965/1d9dbba2-a15a-11e4-9ee4-771b8a20330d.png)

**Comment by cybrox** [comment]
The first issue should not happen, maybe @vikhyat knows more about why this is happening.

As for the second one, this is caused by the still ongoing redesign. Not all pages already have the new header and those who don't look like your first screenshot. We're definitely working on merging all the stuff to the new design though.

**Comment by NuckChorris** [comment]
It's probably linking to an old redesign page which doesn't exist anymore

**Comment by vikhyat** [comment]
/users/edit vs /settings?

I thought we had a redirect set up for the first to point to the latter?

**Comment by vikhyat** [comment]
@vevix can you make a PR with the redirect?

**Comment by vevix** [comment]
Yep, was just waiting on that other PR
