### ISSUE TITLE
Show More on followed stories does not display all users

### ISSUE THREAD

**Issue by UberMouse** [hummingbird-me/hummingbird#416]
It only expands to show another 5 rows and there is no scrollbar to view the rest

![Bug](http://i.imgur.com/mskECyz.png)

**Comment by NuckChorris** [comment]
I think I see a few pixels of the next row at the bottom.  Perhaps this is an issue with overflow in CSS?

**Comment by Wopian** [comment]
>It only expands to show another 5 rows and there is no scrollbar to view the rest

All 65 follows are listed.

> Perhaps this is an issue with overflow in CSS?

There's a `500px` max height on `.comment-text`.

**Comment by vevix** [comment]
Can we get a PR on this? :open_mouth:

**Comment by Wopian** [comment]
:fu: :no_good:

**Comment by AinaM** [comment]
If we change the overflow or max-height for `.comment-text`, it will fix the problem here but I think there will be an issue will all other contents. Because the class `.comment-text` is used at several places.

__Exemple with a simple post content__
Normal : 

![normal_story](https://cloud.githubusercontent.com/assets/5560784/6749160/bc60bb20-ceed-11e4-90f1-8f6e9b72f263.png)

If we add `overflow: auto` on `.comment-text` :

![with oveflow](https://cloud.githubusercontent.com/assets/5560784/6749186/0174d4bc-ceee-11e4-8433-b8e90e7285ce.png)
It also changes here :worried:

Actually, I suppose that when clicking on "_Show more_" / "_Show less_", we should toggle `.full-post` on `.comment-text`. As [here](https://github.com/hummingbird-me/hummingbird/blob/4c7dad8683ddac2ca32c698b767044ba5d9b1cb8/frontend/app/templates/story/comment.hbs#L47) for post content :
``` handlebars
<p {{bind-attr class=":comment-text isExpanded:full-post" }}>
```
This class removes the max-height for `.comment-text`  ! :smile: 

Or, perhaps we could add [here](https://github.com/hummingbird-me/hummingbird/blob/4c7dad8683ddac2ca32c698b767044ba5d9b1cb8/frontend/app/templates/story/followed.hbs#L5) a specific class.
Exemple in template :
``` handlebars
<div class="comment-content comment-followed">
```
In scss : 
``` scss
.comment-followed {
  overflow: auto;
}
```
