### ISSUE TITLE
title of embedded pages converting non-breaking space's (&nbsp;) to text

### ISSUE THREAD

**Issue by sachaw** [hummingbird-me/hummingbird#497]
recently whilst looking at someones profile i noteced this:
![nbsp](https://cloud.githubusercontent.com/assets/11172820/7202528/53eab9e4-e552-11e4-8e7b-f6c986249d6c.PNG)
then when i looked at the source
![nbsp source](https://cloud.githubusercontent.com/assets/11172820/7202530/61975818-e552-11e4-92f6-690c411cef8e.PNG)
not really important but i thought id mention it.

**Comment by vevix** [comment]
I'm going to close this because I don't really think this should be fixed on our end, IMO it should be fixed by the offending website.

We do use [onebox](https://github.com/discourse/onebox) to embed media into our feed posts, maybe you could take this issue up with them.

Others can reopen if they feel I'm wrong.

**Comment by sachaw** [comment]
ok, thanks anyway
