### ISSUE TITLE
replace avatar with the full size transparent one

### ISSUE THREAD

**Issue by sachaw** [hummingbird-me/hummingbird#582]
Today I was on the upcoming anime page and noticed that it uses a full size transparent avatar as against the one used on your library/deshboard etc.

Dashboard: 
![1](https://cloud.githubusercontent.com/assets/11172820/8142849/298286d4-1142-11e5-94e3-ab7cf6f0f29b.PNG)
Upcoming anime page: 
![2](https://cloud.githubusercontent.com/assets/11172820/8142853/36d7bf20-1142-11e5-93df-a76895508051.PNG)

i thought it would look better if they both used the transparent copy so I replaced it on my dashboard.
![capture](https://cloud.githubusercontent.com/assets/11172820/8142861/6021c934-1142-11e5-82bc-b64bc5958d14.PNG)
as a result there was no issues with sizing and it looks much better.
![11](https://cloud.githubusercontent.com/assets/11172820/8142869/fdae9f06-1142-11e5-873f-d009e5a72486.PNG)

**Comment by DNA** [comment]
In the end, it seems we need a better small thumb generation. I'll look into it, but it could take some time since we'll need to redo a lot of avatars :P

**Comment by NuckChorris** [comment]
Yeah the rebuild would probably take 3-4 days

**Comment by sachaw** [comment]
do we need a small thumb, from what i saw the normal looks identical when embedded

**Comment by wopian** [comment]
>do we need a small thumb, from what i saw the normal looks identical when embedded

Avatars are `190x190px` and retain their original format (`.jpeg`, `.png`, `.gif` etc)

The small thumbnails are `100x100px` and are converted to `.jpeg`.

**Comment by sachaw** [comment]
why cant we just make it the 190*190 one? it seems to scale fine in multiple browsers and looks much better on higher dpi screens.

**Comment by wopian** [comment]
Because bandwidth and logic. Making browsers download yours and everyone else's avatars on the dashboard where the size is ~45x45px? and on the forum icons which are even smaller than that (~18px) is a waste of server and client bandwidth.

100 `thumb` images = 3.96 MB that needs to be downloaded
100 `thumb_small` images = 0.47 MB that needs to be downloaded. 

That's a big difference, and is crippling on mobile devices or users on slow network connections.

**Comment by NuckChorris** [comment]
You should also account for caching, though. If the larger size is cached, the smaller size uses more bandwidth. We shouldn't have so many sizes as we do

**Comment by wopian** [comment]
@nuck good point :wink: 

Avatar thumbs around `120px` seem ideal. Since IIRC the largest we go to is around `110px` with the user avatar on profile cover.

**Comment by NuckChorris** [comment]
We also support retina though

**Comment by sachaw** [comment]
@wopian @NuckChorris , I agree with both of your points but i think we should keep going with hummingbird's premium look even if it costs us a little bandwidth in the long run.

**Comment by NuckChorris** [comment]
What?

**Comment by JoshFabian** [comment]
@sachaw I can't say that I agree. If those images aren't being cached, it's a pretty big cost to the user in terms of bandwidth for something that effects the user experience in a very minimal way. 

@NuckChorris @DNA Do we know if it's being cached?

**Comment by NuckChorris** [comment]
It's probably being cached, but most of our images are being very carefully resized to _exactly_ fit each img tag, which results in us having like 3-5 versions of each, many in very similar ranges or with strange names. It's better to have fewer sizes so that (1) we don't waste space on S3 and (2) they can be cached more efficiently.

It's not a problem, it's really just something to keep in mind if somebody wants to rebuild the thumbnailing scheme.

**Comment by DNA** [comment]
I don't know about any cache besides the browser cache. Maybe something on server/cloudfare, but I don't have access to this.

And I think that Nuck brought an interesting topic. Taking Wopian thumbs for example, we would need to cache and store only 39.6kb, instead of 44.32kb. Having less requests on the server if we don't use spdy or http2 is also a good thing.

Of course, I think we would need more data on this matter to take a better decision, but I think it's worth considering.

**Comment by sachaw** [comment]
what ever the solution i think that the image needs transparency support.

**Comment by sachaw** [comment]
Why is this closed, nothing has been done?
