### ISSUE TITLE
Registration/Login Pages

### ISSUE THREAD

**Issue by NuckChorris** [hummingbird-me/hummingbird#667]

**Comment by vevix** [comment]
API/Hookup is complete for our registration process, but still need to support third-party social logins.

**Comment by NuckChorris** [comment]
Yeah, so the implementation iirc will be:

1. Client performs a server-style auth (grant=authorization_code) to Facebook
2. On redirect, the client reads the code out of the query parameters and ships it to server via a special OAuth2 flow on our end

Right?

**Comment by vevix** [comment]
Yep, I’ll be able to send up the Facebook UID of the user, and an active access token (which should be valid for 10 minutes).

I’m not sure we’ll need to send the token up tho, assuming we create a in-the-middle page for social logins to fill out their information instead of importing it directly like what we do in V2.

**Comment by NuckChorris** [comment]
How about `{"token": "fas8yf5as87f5s67agsa76fd5sa78g5sadg5sag98ashfgh769g6sd8fs4df35as46d6f1sdf35gsd21h3h2jfhj45k1f5j", "user_id": "1234567", "site": "facebook"}` for the login, with a relationship to handle manipulation of the connections?

**Comment by JoshFabian** [comment]
Something else to consider is what happens when a user attempts to social connect after they already have an account. Their registration will fail (email already taken) I think we'll want to do two things: 

1) Ensure that a social account is not 'locked' or tied to a ghost account and that user can still login and connect to their current account from the settings page.
2) Show a message on registration fail telling them that they already have an account and either ask them to login (and connect the account) OR ask them to login and go to settings to connect.

**Comment by NuckChorris** [comment]
ghost account?  locked?

**Comment by JoshFabian** [comment]
Ghost account as in, we don't want the social profile tied to an account that doesn't exist. Not sure if that's an actual concern, but being that one social account is tied to one user, we wouldn't want it so that their failed registration causes that social profile to now be unavailable to attach to another account.
