### ISSUE TITLE
User blocking model

### ISSUE THREAD

**Issue by NuckChorris** [hummingbird-me/hummingbird#747]
Right now, user blocking doesn't need to actually be applied (feeds don't exist yet!)

But we can build the model.  Hell, it... might just be a two-column table.

**Comment by pixeldesu** [comment]
I don't know how the relationship system works on HB right now, but why not use a kind of 3 way "Relationship" model here, based on types?

3 way, as in:
- An _active_ and a _passive_ **follow** relationship. (only being here to properly list you followings/followers with has_many through)
- A one-way **block** relationship (because blocking does not include both sides, the effects from it can simply be checked on later)

Kind-of example of what I'm talking about available here:
https://github.com/stellate/stellate/blob/master/app/models/user.rb (note: it can be done better than here, but just to get the general idea of it)

**Comment by NuckChorris** [comment]
Following and blocking are two very different things such just happen to have the same two columns. Why merge them when they're easily modeled separately? It just complicates the code to shove them in the same table

**Comment by DNA** [comment]
Isn't it the same as #655?

**Comment by NuckChorris** [comment]
That's a meta-issue, this is specific to the server-side implementation of it
