### ISSUE TITLE
Can't set it up 

### ISSUE THREAD

**Issue by Sshuichi** [hummingbird-me/hummingbird#761]
**Description:**
ERROR: In file './docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.
**Steps to reproduce:**
run `./bin/setup && ./bin/start`
**Screenshots (if applicable):**
N.A
**OS and Browser:**
Ubuntu 16.04

**Comment by NuckChorris** [comment]
What's `docker-compose -v` say?

**Comment by Sshuichi** [comment]
`docker-compose version 1.5.2, build unknown`

**Comment by Sshuichi** [comment]
Updated to 1.8 and it's working now.

**Comment by NuckChorris** [comment]
Indeed, we need a relatively modern Docker install. They introduced the V2 format about a year ago.

It's recommended that you follow the official Docker instructions for install instead of just grabbing from your package manager's default repos. I believe Docker has their own apt sources with the latest stuff
