### ISSUE TITLE
small cosmetic issue with links

### ISSUE THREAD

**Issue by kufii** [hummingbird-me/hummingbird#762]
I've noticed a small cosmetic issue with links on hummingbird. You know when you hover over a link it turns from orange to blue? If you middle click the link, it'll never turn back to orange, even if you move your mouse away.

Not a big deal but thought I should bring it up

**Comment by NuckChorris** [comment]
This is part of your browser: it focuses the link, which turns it orange.  If you want it to turn back, click out of it.

**Comment by kufii** [comment]
is the animation pure css? would it not make sense to use :hover instead of :focus?

**Comment by NuckChorris** [comment]
Then it would have no indication of focus.  Anyways, we aren't working on V2 any more, if this is gonna be changed it'll happen in V3, but it's up to @JoshFabian.

Personally I'm against it, there's only like 7 people in the whole world who actually middle click links, and it's your browser's fault for giving it focus from that.

**Comment by kufii** [comment]
fair enough, but man you're missing out, middle clicking links is the absolute best

**Comment by NuckChorris** [comment]
Ye, I don't even have a mouse or trackpad which supports middle clicking any more lol

**Comment by cybrox** [comment]
I'm going to close this, since my middle mouse button is broken and I therefore feel offended by this request.

Jokes aside, thanks for reporting. As @NuckChorris already mentioned though, we are not working on V2 anymore, and I will leave all design decisions in that aspect for V3 to Josh. Feel free to reopen this after the V3 launch if it still bugs you but I don't think there's much we could do, considering you usually want a `:hover` and `:focus` indicator.
