### ISSUE TITLE
Can't get bin/setup working on windows

### ISSUE THREAD

**Issue by akpark** [hummingbird-me/hummingbird#767]
Don't know if my setup is right. Never developed on windows.
I git cloned the repository, ran `bin/setup`, the client and server are both downloaded properly into hummingbird, but it errors out when trying to run docker.
I have docker running on a vm (Oracle Virtual Box) through Docker Quickstart Terminal.

Getting `Couldn't connect to Docker daemon - you might need to run docker-machine start default`.
Any help appreciated! Thanks!

**Comment by cybrox** [comment]
Hey. Fist, since you got to the point where the setup attempts to access the docker containers, you won't have to go through all of `bin/setup` again but can simply `bin/rebuild && bin/start`, after the issue you are facing with Docker is solved.

Now, I'm not terribly familiar with Docker for Windows, because even on my Windows PC, I would rather set up a full fetched VM with Linux for development. Anyways, the most likely thing I can think of is, that the docker installer did not automatically start a machine (or screwed something up in the process of doing so). Can you try running `docker-machine restart default` in your docker quickstart terminal? Alternatively, you can do `docker-machine ls` there first, in order to check if a machine is active. Usually, `default` should be running.

**Comment by JoshFabian** [comment]
Might be good to create a task so that we can circle back around at some point and add proper windows support to the set-up script.

**Comment by vevix** [comment]
I think its worth recommending that devs on Windows use [Docker for Windows](https://docs.docker.com/docker-for-windows/).

Seems @akpark is using an older setup with docker toolbox.

**Comment by cybrox** [comment]
If you don't have docker installed, `bin/setup` actually points you to Docker for Windows. I will go over the wiki and README later and put a note in there as well.

```
- If you are on Windows, check out Docker for Windows at https://docs.docker.com/docker-for-windows/
```

**Comment by akpark** [comment]
:+1: Thanks guys.
Unfortunately, I'm using Windows 10 Home edition, and Docker for Windows requires Pro, Enterprise, and Education.

Also followed cybrox's steps, but no luck :/ even though default was running. I think I'm just going to set up a vm and run everything on linux as @cybrox mentioned.
